services:
  postgresdb:
    image: postgres:latest
    container_name: postgresql-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin # Remplacez par le nom d'utilisateur souhaité
      POSTGRES_PASSWORD: adminpwd # Remplacez par le mot de passe souhaité
      POSTGRES_DB: db # Remplacez par le nom de la base de données souhaité
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  api:
    container_name: spice-world-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    environment:
      DATABASE_URL: postgresql://admin:adminpwd@postgresdb:5432/db
    restart: always
